### ISSUE TITLE
Extract PanelOLS functionality

### ISSUE THREAD

**Issue by crahal** [centre-for-care/nrobust#11]
The current PanelOLS is _really_ slow, almost certainly because it's doing a bunch of things that we don't need. Suggestion to strip out the actual estimator from its wrapper and make an equivilent to the simple_ols() which is called something like simple_panel(): hopefully shouldn't be too hard to do!

**Comment by dhvalden** [comment]
deal! I'll take that issue. I'll investigate alternatives and I'll report here.

**Comment by dhvalden** [comment]
feature added. We added a fixed effects estimator.
