### ISSUE TITLE
Some warnings to investigate

### ISSUE THREAD

**Issue by crahal** [centre-for-care/nrobust#21]
anaconda3\lib\site-packages\nrobust\replication_data_prep.py:49: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once 
using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ASC_df['dcareNew*c.lrealgs'] = ASC_df['dcareNew'] * ASC_df['lrealgs']

anaconda3\lib\site-packages\nrobust\replication_data_prep.py:50: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once 
using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  ASC_df['constant'] = 1

anaconda3\lib\site-packages\nrobust\models.py:79: MissingValueWarning: Missing values found in data. Listwise deletion will be applied
  warnings.warn('Missing values found in data. Listwise deletion will be applied',

**Comment by dhvalden** [comment]
all of this are expected and healthy. The first ones are not ours, and are only there for the data preparation function. the last warning is ours and is intended.
